CREATE TABLE CANDIDATO (
  CHAVE_CANDIDATO bigserial PRIMARY KEY,
  NOME_CANDIDATO VARCHAR(255) NOT NULL,
  CPF_CANDIDATO VARCHAR(14) NOT NULL UNIQUE,
  CHAVE_PARTIDO INTEGER,
  DATA_NASIMENTO date
)

