CREATE TABLE TD_ELEICAO (
  CHAVE_ELEICAO bigserial PRIMARY KEY,
  NOME_ELEICAO VARCHAR(255) NOT NULL,
  ANO_ELEICAO VARCHAR(4) NOT NULL UNIQUE,
  DATA_ELEICAO date not null,
  CODIGO_ELEICAO INTEGER not null
)

